# Generated by Django 4.1.1 on 2022-10-03 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='File',
        ),
    ]
